apiVersion: v1
kind: Service
metadata:
  name: mesa-solidaria-wrk
  namespace: namespace-workflow-1708797537480
spec:
  type: LoadBalancer
  selector:
    app: mesa-solidaria-wrk
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000