apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesasolidariawrkpoddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesasolidariawrkpod
  template:
    metadata:
      labels:
        app: mesasolidariawrkpod
    spec:
      containers:
        - name: mesasolidariawrkpod
          image: darakimberlys/mesasolidariawrk:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: mesasolidariawrkpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer